All tasks

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,39 +1,33 @@
 #!/usr/bin/env bash
-# This script installs and configures Nginx on an Ubuntu machine
+#install ngix and have a file that returns the string "Hello World  inside
 
-# Update package lists
-sudo apt-get update
-
-# Install Nginx
+sudo apt-get update -y && \
 sudo apt-get install -y nginx
-
-# Remove the default Nginx configuration
-sudo rm /etc/nginx/sites-enabled/default
-
-# Create custom Nginx configuration file
-cat << EOF | sudo tee /etc/nginx/sites-available/default
-server {
-    listen 80 default_server;
-    listen [::]:80 default_server;
-
-    root /var/www/html;
-    index index.html index.htm;
-
-    server_name _;
-
-    location / {
-        try_files \$uri \$uri/ =404;
+if [ $? -eq 0 ]
+then
+    echo -e \
+"http {
+    root /var/www/school;
+    index index.html;
+    server {
+        listen 80;
+        location \ {
+        }
     }
 }
-EOF
-
-# Create the HTML file with the desired content
-echo "Hello World!" | sudo tee /var/www/html/index.html
-
-# Enable the new configuration
-sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
-
-# Restart Nginx
-sudo service nginx restart
-
-echo "Nginx has been configured and is now running."
+events {
+}" > /etc/nginx/nginx.conf
+    mkdir -p /var/www/school
+    echo "Hello World!" > \
+	/var/www/school/index.html
+    service nginx start
+    if [ $? -ne 0 ]
+    then
+	"Problem starting nginx"
+	exit 1
+    fi
+else
+    echo "Could not install nginx"
+    exit 1
+fi
+exit 0
